theme: jekyll-theme-minimal
title: The Space Journalism Handbook
description: There's no manual for doing journalism with satellite data. Let's make one.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
